USE BusBase;
GO

CREATE OR ALTER FUNCTION BusBase.fnGenerateName()
RETURNS VARCHAR(50)
AS
BEGIN
    DECLARE @Name VARCHAR(50) = (SELECT TOP 1 [Name] FROM BusBase.GeneratedNames ORDER BY (SELECT NewId FROM BusBase.vwNewId))
    RETURN @Name
END;

