USE BusBase
GO

DROP TABLE IF EXISTS BusBase.VehicleTypes
DROP TABLE IF EXISTS BusBase.Vehicles
DROP TABLE IF EXISTS BusBase.TicketTypes
DROP TABLE IF EXISTS BusBase.Tickets
DROP TABLE IF EXISTS BusBase.Addresses
DROP TABLE IF EXISTS BusBase.Stations
DROP TABLE IF EXISTS BusBase.VehicleTypes
DROP TABLE IF EXISTS BusBase.Vehicles
DROP TABLE IF EXISTS BusBase.TicketTypes
