USE BusBase
GO

DROP TABLE IF EXISTS BusBase.Tickets
DROP TABLE IF EXISTS BusBase.Stations
DROP TABLE IF EXISTS BusBase.BusLine
DROP TABLE IF EXISTS dbo.Driver
DROP TABLE IF EXISTS dbo.Buses
DROP TABLE IF EXISTS dbo.BusStation
DROP TABLE IF EXISTS dbo.BusLineItem
DROP TABLE IF EXISTS BusBase.Driver
