USE BusBase
GO

CREATE TABLE BusLineItem
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	LineId INT NOT NULL,
	BusStopId INT NOT NULL,
	IsWithRoof BIT,
	-- WorkingHours
	CreatedDate DATETIME DEFAULT(GETDATE()) 
)
GO